/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Crank_Signal.h"
#include "Crank_Output_ecm_aliases.h"
#include "Crank_Output_ecm.h"
#include "Cam_Output_aliases.h"
#include "Cam_Output.h"
#include "Cam_signal.h"
#include "Crank_Input_Diesel_aliases.h"
#include "Crank_Input_Diesel.h"
#include "isr_CKP_counter.h"
#include "timer_clock.h"
#include "Control_Reg_1.h"
#include "Timer_Sytem.h"
#include "Timer_1.h"
#include "isr_Not_Runing.h"
#include "Thermistor_1.h"
#include "VDAC8_1.h"
#include "ADC_DelSig_1.h"
#include "Opamp_1.h"
#include "AMux_1.h"
#include "Rref10Kpin1_aliases.h"
#include "Rref10Kpin1.h"
#include "Rref_and_thermistor_between_aliases.h"
#include "Rref_and_thermistor_between.h"
#include "Thermoster_Vss_aliases.h"
#include "Thermoster_Vss.h"
#include "PWM_1_FANCONTROLLER.h"
#include "Fan_1_aliases.h"
#include "Fan_1.h"
#include "Glow_Plug_pin_aliases.h"
#include "Glow_Plug_pin.h"
#include "Clock_1.h"
#include "Control_Reg_2.h"
#include "Clock_2.h"
#include "MASS_AIRFLOW.h"
#include "Mass_Air_Voltage_Output_aliases.h"
#include "Mass_Air_Voltage_Output.h"
#include "mass_air.h"
#include "Battery_interlock_aliases.h"
#include "Battery_interlock.h"
#include "Temp_Checker.h"
#include "Glow_plug_indicator_aliases.h"
#include "Glow_plug_indicator.h"
#include "Cold_Advance_aliases.h"
#include "Cold_Advance.h"
#include "Spare_1_aliases.h"
#include "Spare_1.h"
#include "Spare_2_aliases.h"
#include "Spare_2.h"
#include "Clock_3.h"
#include "Crank_Signal_Wave1_DMA_dma.h"
#include "Crank_Signal_Wave2_DMA_dma.h"
#include "Crank_Signal_VDAC8.h"
#include "Crank_Signal_BuffAmp.h"
#include "Cam_signal_Wave1_DMA_dma.h"
#include "Cam_signal_Wave2_DMA_dma.h"
#include "Cam_signal_VDAC8.h"
#include "Cam_signal_BuffAmp.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

